[package]
name = "f4yking/ragdollr6"
description = "R6 Ragdoll Module."
version = "2.0.0"

license = "MIT"
authors = ["F4YKING"]

realm = "server"
registry = "https://github.com/UpliftGames/wally-index"

exclude = ["**"]
include = ["RagdollR6", "RagdollR6/*", "default.project.json", "wally.toml"]

[dependencies]
Trove = "sleitnick/trove@1.0.1"