[package]
name = "f4yking/ragdollr6"
description = "R6 Ragdoll Module."
version = "1.0.0"
license = "MIT"
authors = ["F4YKING"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
Trove = "sleitnick/trove@1.0.1"